### PR TITLE
Added debug binary to Docker image

### PR DESCRIPTION
**Pull request by ChrisTimperley**
Linked to https://github.com/squaresLab/BugZoo/issues/334

### CODE REVIEW

**Comment by ChrisTimperley** [comment]
@pdreiter, I don't seem to be able to tag you as a reviewer. Can you check that this works for you?

**Comment by pdreiter** [comment]
I'm not sure what I'm doing wrong, but when I launch:
```docker build .```
from the directory with the genprog dockerfile, I get this error:
```
Step 8/10 : RUN mkdir bin &&     eval $(opam config env) &&     make && 	make -C src repair.byte &&     mv src/repair bin/genprog &&     mv src/repair.byte bin/genprog.byte &&     ln -s bin/genprog bin/repair &&     mv src/distserver bin/distserver &&     mv src/nhtserver bin/nhtserver
 ---> Running in 05cf58a13e28
[WARNING] Running as root is not recommended
make -C src/ 
make[1]: Entering directory '/opt/genprog/src'
/bin/sh: 1: file: not found
make[1]: Leaving directory '/opt/genprog/src'
make[1]: *** No rule to make target '/home/bss-lab-1/.opam/default/.opam-switch/sources/cil.1.7.3/_build/src/cil.cmx', needed by 'global.cmx'.  Stop.
Makefile:10: recipe for target 'doc' failed
make: *** [doc] Error 2
The command '/bin/sh -c mkdir bin &&     eval $(opam config env) &&     make && make -C src repair.byte &&     mv src/repair bin/genprog &&     mv src/repair.byte bin/genprog.byte &&     ln -s bin/genprog bin/repair &&     mv src/distserver bin/distserver &&     mv src/nhtserver bin/nhtserver' returned a non-zero code: 2
```

**Comment by pdreiter** [comment]
> I'm not sure what I'm doing wrong, but when I launch:
> `docker build .`
> from the directory with the genprog dockerfile, I get this error:
> 
> ```
> Step 8/10 : RUN mkdir bin &&     eval $(opam config env) &&     make && 	make -C src repair.byte &&     mv src/repair bin/genprog &&     mv src/repair.byte bin/genprog.byte &&     ln -s bin/genprog bin/repair &&     mv src/distserver bin/distserver &&     mv src/nhtserver bin/nhtserver
>  ---> Running in 05cf58a13e28
> [WARNING] Running as root is not recommended
> make -C src/ 
> make[1]: Entering directory '/opt/genprog/src'
> /bin/sh: 1: file: not found
> make[1]: Leaving directory '/opt/genprog/src'
> make[1]: *** No rule to make target '/home/bss-lab-1/.opam/default/.opam-switch/sources/cil.1.7.3/_build/src/cil.cmx', needed by 'global.cmx'.  Stop.
> Makefile:10: recipe for target 'doc' failed
> make: *** [doc] Error 2
> The command '/bin/sh -c mkdir bin &&     eval $(opam config env) &&     make && make -C src repair.byte &&     mv src/repair bin/genprog &&     mv src/repair.byte bin/genprog.byte &&     ln -s bin/genprog bin/repair &&     mv src/distserver bin/distserver &&     mv src/nhtserver bin/nhtserver' returned a non-zero code: 2
> ```
> 
> i'll look into this a bit more.

@jlacomis and @ChrisTimperley 
So we have a couple of problems:

1. The default Makefile build infrastructure refers to docs directory which isn't added to the docker environment [easy fix - `ADD docs docs`] 
    - Accounting for this fix, we now get the following error:
```Error: Unbound value String.lowercase_ascii```
2. So, the above error indicates we have conflicting configuration between Ubuntu 16.04, Ocaml, and GenProg requirements:
    - GenProg source refers to `String.lowercase_ascii`, which is only available in ocaml version `4.03`.
    - Ubuntu 16.04LTS seems to only support ocaml package: ocaml (4.02.3-5ubuntu2), I double checked the Ubuntu official package releases, as well as I checked `opam update && opam upgrade` which doesn't enable a later version of ocaml in opam.

So, either we'll need to update the dockerfile to manually install the ocaml 4.03 package - or update to Ubuntu 18.04, which resolves all this, but has some other idiosyncrasies.

I have a local version of the Dockerfile that works with `Ubuntu 18.04` and uses `opam 1.2.2`, but I would argue that it would be more beneficial to update to `opam >=2.0` for longevity purposes - i have some local Dockerfile changes that support `opam 2.0`.

**Comment by pdreiter** [comment]
So I built and tried to use this docker image in the new gzip docker build infrastructure by adding "FROM: <myimage:mytag>" and I have been getting some weird results, depending on the placement of the inclusion.  I can't seem to get the `bugzoo bug build` to build gzip with this image.

**Comment by ChrisTimperley** [comment]
> @ChrisTimperley
> So I built and tried to use this docker image in the new gzip docker build infrastructure by adding "FROM: myimage:mytag" and I have been getting some weird results. Regardless of the placement of the `FROM`, I can't seem to get the `bugzoo bug build` to build gzip with this genprog image.
> I don't know, i think it may be something to do with Ubuntu 18.04 or something else I could be doing wrong with docker (??).

I'm not quite sure that I follow. Can you provide an example of how you're using this with the Gzip images?

**Comment by pdreiter** [comment]
> > @ChrisTimperley
> > So I built and tried to use this docker image in the new gzip docker build infrastructure by adding "FROM: myimage:mytag" and I have been getting some weird results. Regardless of the placement of the `FROM`, I can't seem to get the `bugzoo bug build` to build gzip with this genprog image.
> > I don't know, i think it may be something to do with Ubuntu 18.04 or something else I could be doing wrong with docker (??).
> 
> I'm not quite sure that I follow. Can you provide an example of how you're using this with the Gzip images?


Sure thing:
I built the docker image locally:
```
git clone <genprog-repo>
cd <local genprog-repo>
docker build -t my_genprog:latest .
``
and in the Dockerfile.gzip, I added 
`FROM my_genprog:latest`

I moved this line around the dockerfiles and got some weird behavior, i'm guessing because ubuntu:18.04 trumps 16.04.  
I also found that the gzip code does not compile with ubuntu 18.04 [the bootstrap failed - i think gcc-7 does not play well the build] -  it was a nightmare.

**Comment by ChrisTimperley** [comment]
> and in the Dockerfile.gzip of a local bugzoo source, I added
> `FROM my_genprog:latest`

Ah. This (tool) image isn't intended to be used as a base image for a bug scenario. In general, you either want to:
* mount the tool via `--tool` in BugZoo. Internally, that will dynamically mount `/opt/genprog` inside the container for the bug scenario.
* if you want to bake the tool binaries into a bug scenario image -- I wouldn't recommend this unless you're debugging -- then you can use [a multi-stage build](https://docs.docker.com/develop/develop-images/multistage-build/) to import the binaries:
```
COPY --from=my_genprog:latest /opt/genprog /opt/genprog
```
